# Site settings
title: Means to meaning
email: vlasto.pis@gmail.com
description: "A (not so) random assortment of articles and things related to computational statistics"
baseurl: ""
url: "http://senorsalchicha.github.io"
github_username:  senorsalchicha

# Build settings
markdown: kramdown
permalink: pretty
pygment: true
highlighter: rouge
